# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: otogram_development
  username: pguser
  password: pguser

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
